<?php
namespace Littled\Tests\Base;

use PHPUnit\Framework\TestCase;

class DatabaseTestCase extends TestCase
{
	public static function setUpBeforeClass()
	{
		parent::setUpAfterClass(); // TODO: Change the autogenerated stub
	}

	public static function tearDownAfterClass()
	{
		parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
	}
}