<?php
namespace LittledTests\Base;

use PHPUnit\Framework\TestCase;

class DatabaseTestCase extends TestCase
{
	public static function setUpBeforeClass() : void
	{
	}

	public static function tearDownAfterClass() : void
	{
		parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
	}
}