<?php
namespace Littled\Tests\TestHarness\PageContent\SiteSection;

use Littled\PageContent\SiteSection\ContentRoute;


class ContentRouteTestHarness extends ContentRoute
{
    /**
     * @inheritDoc
     * Public interface for tests.
     */
    public static function explodeRouteString(string $route): array
    {
        return parent::explodeRouteString($route); // TODO: Change the autogenerated stub
    }
}