DELIMITER $$
CREATE OR REPLACE PROCEDURE `addressUpdate`(
    INOUT p_address_id INT,
    IN p_salutation VARCHAR(6),
    IN p_first_name VARCHAR(50),
    IN p_last_name VARCHAR(50),
    IN p_address1 VARCHAR(200),
    IN p_address2 VARCHAR(200),
    IN p_city VARCHAR(100),
    IN p_state_id INT,
    IN p_non_us_state VARCHAR(100),
    IN p_zip VARCHAR(20),
    IN p_country VARCHAR(100),
    IN p_home_phone VARCHAR(20),
    IN p_work_phone VARCHAR(20),
    IN p_mobile_phone VARCHAR(20),
    IN p_fax VARCHAR(20),
    IN p_email VARCHAR(100),
    IN p_organization VARCHAR(100),
    IN p_title VARCHAR(50),
    IN p_location VARCHAR(200),
    IN p_url VARCHAR(255),
    IN p_latitude FLOAT,
    IN p_longitude FLOAT,
    IN p_notes TEXT
)
BEGIN

INSERT INTO `address` (
    `id`,
    `salutation`,
    `first_name`,
    `last_name`,
    `address1`,
    `address2`,
    `city`,
    `state_id`,
    `non_us_state`,
    `zip`,
    `country`,
    `home_phone`,
    `work_phone`,
    `mobile_phone`,
    `fax`,
    `email`,
    `organization`,
    `title`,
    `location`,
    `url`,
    `latitude`,
    `longitude`,
    `notes`
) VALUES (
    p_address_id,
    p_salutation,
    p_first_name,
    p_last_name,
    p_address1,
    p_address2,
    p_city,
    p_state_id,
    p_non_us_state,
    p_zip,
    p_country,
    p_home_phone,
    p_work_phone,
    p_mobile_phone,
    p_fax,
    p_email,
    p_organization,
    p_title,
    p_location,
    p_url,
    p_latitude,
    p_longitude,
    p_notes
)
ON DUPLICATE KEY UPDATE
    salutation = p_salutation,
    first_name = p_first_name,
    last_name = p_last_name,
    address1 = p_address1,
    address2 = p_address2,
    city = p_city,
    state_id = p_state_id,
    non_us_state = p_non_us_state,
    zip = p_zip,
    country = p_country,
    home_phone = p_home_phone,
    work_phone = p_work_phone,
    mobile_phone = p_mobile_phone,
    fax = p_fax,
    email = p_email,
    organization = p_organization,
    title = p_title,
    location = p_location,
    url = p_url,
    latitude = p_latitude,
    longitude = p_longitude,
    notes = p_notes;

IF p_address_id IS NULL THEN
    SELECT LAST_INSERT_ID() INTO p_address_id;
END IF;

END $$
