<?php
namespace Littled\Tests\TestHarness\API;

use Littled\API\APIListingsRoute;


class APIListingsRouteTestHarness extends APIListingsRoute
{
    public function initializeFiltersObject(?int $content_type_id = null)
    {
        parent::initializeFiltersObject($content_type_id); // TODO: Change the autogenerated stub
    }
}