<?php
namespace Littled\Tests\TestHarness\API;

use Littled\API\APIListingsRoute;
use Littled\Tests\TestHarness\PageContent\ContentControllerTestHarness;


class APIListingsRouteTestHarness extends APIListingsRoute
{
    protected static array $route_parts = ['api', 'listings'];
    protected static string $controller_class = ContentControllerTestHarness::class;

    public function initializeFiltersObject(?int $content_type_id = null)
    {
        parent::initializeFiltersObject($content_type_id); // TODO: Change the autogenerated stub
    }
}